### PR TITLE
Alternative script for testing Bleichenbacher timing vulnerability

### PR DESCRIPTION
**Pull request by tomato42**
### Description

more tests for checking the timing variant of Bleichenbacher

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [x] NSS
  - [ ] GnuTLS
- [x] required version of tlslite-ng updated in requirements.txt and README.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859)

### CODE REVIEW

**Review by t184256 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859)* status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @tomato42)

___
*[`scripts/marvin-ciphertext-generator.py` line 0 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NembnXf3jkxLCniPJPd:-NembnXf3jkxLCniPJPe:b3en8t5) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L0)):*
this is the first non-`test-'-prefixed file in scripts, and it has a different "interface". should it rather live someplace else?
___
*[`scripts/marvin-ciphertext-generator.py` line 17 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemb_X-556Kmm6VoLxE:-Nemb_X-556Kmm6VoLxF:blid2mj) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L17)):*
> ```Python
> 
> 
> version = 5
> ```

Minor: why start at 5?
___
*[`scripts/marvin-ciphertext-generator.py` line 63 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemdBi85e6WDznwd1kS:-NemdBi98tm-xmv2y0BC:b-hlg7yh) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L63)):*
> ```Python
>     argv = sys.argv[1:]
>     opts, args = getopt.getopt(argv,
>                                "x:X:n:a:l:l:o:i:C:",
> ```

I only see -o being used
___
*[`scripts/marvin-ciphertext-generator.py` line 117 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Neme2vv6e29Yi34mR-b:-Neme2vv6e29Yi34mR-c:byhch8n) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L117)):*
> ```Python
>         srv_key, srv_cert.publicKey, pms_len, pms_tls_version)
>     ciphertexts = marvin_gen.generate()
>     print("Ciphertexts generated.")
> ```

Minor: confusing in conjunction with the next line
___
*[`scripts/marvin-ciphertext-generator.py` line 135 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemhU-YD4FNT_EF2wuT:-NemhU-YD4FNT_EF2wuU:b-avom6u) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L135)):*
> ```Python
>         test_classes = log.get_classes()
> 
>         status = [0, len(test_classes) * repetitions, Event()]
> ```

not a fan of this API. consider an struct-like object to pass to a reporter or turning that into attributes of a reporter instance
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 124 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemio5n-sI5-3qT7I56:-Nemio5n-sI5-3qT7I57:bolhubz) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d8dd427876706d7d1ea06653e43f7e58827a321e/scripts/test-bleichenbacher-timing-marvin.py#L124)):*
> ```Python
>     malformed ciphertext.
>     """
>     n = priv_key.n
> ```

I don't see you using n further, just `numbytes(n)`. Maybe assign that to a variable?
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 9 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemzqbv94xszzQzRCGx:-Nemzqbv94xszzQzRCGy:bmfbaq2) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/test-bleichenbacher-timing-marvin.py#L9)):*
> ```Python
> import getopt
> import os
> import math
> ```

~12 unused imports
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 138 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemrfAB9ZUSqG5XoORV:-NemrfAB9ZUSqG5XoORW:b-5v9w20) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/test-bleichenbacher-timing-marvin.py#L138)):*
> ```Python
>     argv = sys.argv[1:]
>     opts, args = getopt.getopt(argv,
>                                "h:p:e:x:X:n:a:l:l:o:i:C:",
> ```

two `l`s
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 237 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemtn2Z4lHkQ2cJz6jd:-Nemtn2Z4lHkQ2cJz6je:b-vyv498) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/test-bleichenbacher-timing-marvin.py#L237)):*
> ```Python
>     if is_valid_hostname(host) and not no_sni:
>         cln_extensions[ExtensionType.server_name] = \
>             SNIExtension().create(bytearray(host, 'ascii'))
> ```

`'idna'` =D
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 566 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemvp2UA5V9G2Tua9_p:-Nemvp2UA5V9G2Tua9_q:bbxz6nw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/test-bleichenbacher-timing-marvin.py#L566)):*
> ```Python
>             else:
>                 print("Statistical analysis exited with {0}".format(ret_val))
>         else:
> ```

since this branch aborts, you can change the order of them and have the other one dedented.
___
*[`tlsfuzzer/utils/rsa.py` line 70 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemlR4GEXIRVdhj-YRE:-NemlR4GEXIRVdhj-YRF:brodsiq) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/tlsfuzzer/utils/rsa.py#L70)):*
> ```Python
> def _encrypt_with_fuzzing(pub_key, plaintext, padding_subs, padding_byte):
>     old_addPKCS1Padding = pub_key._addPKCS1Padding
>     public_key = fuzz_pkcs1_padding(pub_key, padding_subs, None, padding_byte)
> ```

Not a fan of that API either. Could it return the function unattached, maybe? Attach, but to a copy?
___
*[`tlsfuzzer/utils/rsa.py` line 84 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemwblxC9e-8Tb0D9g0:-NemwblxC9e-8Tb0D9g1:by5geqh) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/tlsfuzzer/utils/rsa.py#L84)):*
> ```Python
>     or invalid ciphertexts that have synthethic ciphertexts of specified
>     length. All ciphertexts will also require the same number of bytes to
>     represent.
> ```

"to represent them"?
___
*[`tlsfuzzer/utils/rsa.py` line 168 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemnN990BDAuVRWBmwd:-NemnN990BDAuVRWBmwe:b-gmfk29) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/tlsfuzzer/utils/rsa.py#L168)):*
> ```Python
> 
>         # then invalid one, with version byte set to 1
>         subs = {0: 1}
> ```

why spend a line on that? in general, I think this part can be more compact, `ret[description_doubling_as_comment] = shorter_func_name({0: 1})`
___
*[`tlsfuzzer/utils/rsa.py` line 237 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NempzbgE1tTBaMqL1en:-NempzbgE1tTBaMqL1eo:b-7cf2bd) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/tlsfuzzer/utils/rsa.py#L237)):*
> ```Python
> 
>         # very short PKCS padding
>         subs = {}
> ```

That's a `dict(enumerate([0] * 41 + [2]))`

**Review by tomato42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859)* status: 0 of 7 files reviewed, 14 unresolved discussions (waiting on @t184256)

___
*[`scripts/marvin-ciphertext-generator.py` line 17 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemb_X-556Kmm6VoLxE:-NenNU6sBRarTVOcInwu:b-oisuu9) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L17)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

Minor: why start at 5?
</blockquote></details>

because internal development and changes over time in this PR
___
*[`scripts/marvin-ciphertext-generator.py` line 135 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemhU-YD4FNT_EF2wuT:-NenNgL09B0QpW69CuIY:b9qaq72) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L135)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

not a fan of this API. consider an struct-like object to pass to a reporter or turning that into attributes of a reporter instance
</blockquote></details>

it's already used all over the place, so I would have to support both APIs, I don't think it's worth changing.
Those can't be attributes as we're changing them in-place, and we can't change a value of an int without using a different object in python.
___
*[`scripts/marvin-ciphertext-generator.py` line  at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NembnXf3jkxLCniPJPd:-NenN9zy1Au9svYAI8a8:bvog5u) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/marvin-ciphertext-generator.py#L)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

this is the first non-`test-'-prefixed file in scripts, and it has a different "interface". should it rather live someplace else?
</blockquote></details>

the lack of test prefix is intentional: it's not used for testing TLS servers, if it should live in some other place, I don't know... it is a script that uses tlsfuzzer api...
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 124 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemio5n-sI5-3qT7I56:-NenOMdM57lecXE-nts4:b-ofokn2) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d8dd427876706d7d1ea06653e43f7e58827a321e/scripts/test-bleichenbacher-timing-marvin.py#L124)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

I don't see you using n further, just `numbytes(n)`. Maybe assign that to a variable?
</blockquote></details>

it is moved to separate module in later patch
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 237 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemtn2Z4lHkQ2cJz6jd:-NenOgUm1-ypJRfI0tg2:b3kre) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/test-bleichenbacher-timing-marvin.py#L237)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

`'idna'` =D
</blockquote></details>

?
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 566 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemvp2UA5V9G2Tua9_p:-NenOnR-C6uHx_0qrHeP:bdaek36) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/scripts/test-bleichenbacher-timing-marvin.py#L566)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

since this branch aborts, you can change the order of them and have the other one dedented.
</blockquote></details>

good point
___
*[`tlsfuzzer/utils/rsa.py` line 70 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemlR4GEXIRVdhj-YRE:-NenOvf_B2RzolZLeK6K:b-3vv3yk) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/738e79cd87da1bdee233fe0d340ca3a7d6219db6/tlsfuzzer/utils/rsa.py#L70)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

Not a fan of that API either. Could it return the function unattached, maybe? Attach, but to a copy?
</blockquote></details>

it's reusing the code from tlsfuzzer, so needs to follow the same API...

**Review by tomato42 — COMMENTED** [review]
@t184256 updated, please re-review

> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-:-Nf2PpWUCZLFf_q17tSV:b-3yx8c6)* status: 0 of 7 files reviewed, 10 unresolved discussions (waiting on @t184256 and @tomato42)

___
*[`scripts/marvin-ciphertext-generator.py` line 63 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemdBi85e6WDznwd1kS:-Nf2IwT63gHXqUcf_dAX:bb7f2mf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/scripts/marvin-ciphertext-generator.py#L63)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

I only see -o being used
</blockquote></details>

done
___
*[`scripts/marvin-ciphertext-generator.py` line 117 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Neme2vv6e29Yi34mR-b:-Nf2JI6aBG1mjjHm5vYW:bb7f2mf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/scripts/marvin-ciphertext-generator.py#L117)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

Minor: confusing in conjunction with the next line
</blockquote></details>

done
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 9 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemzqbv94xszzQzRCGx:-Nf2KRy58ki0T1-Q8gi0:bb7f2mf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/scripts/test-bleichenbacher-timing-marvin.py#L9)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

~12 unused imports
</blockquote></details>

done
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 138 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemrfAB9ZUSqG5XoORV:-Nf2KmPE9NroiQPjYUug:bb7f2mf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/scripts/test-bleichenbacher-timing-marvin.py#L138)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

two `l`s
</blockquote></details>

done
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 237 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemtn2Z4lHkQ2cJz6jd:-Nf2KpDM3Wieq6PXNubj:bc01irs) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/scripts/test-bleichenbacher-timing-marvin.py#L237)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

?
</blockquote></details>

that wouldn't work on python2 with internationalised values anyway:
```
\>>> bytearray('łódź', 'idna')  
Traceback (most recent call last):  
 File "<stdin>", line 1, in <module>  
 File "/usr/lib64/python2.7/encodings/idna.py", line 162, in encode  
   result.append(ToASCII(label))  
 File "/usr/lib64/python2.7/encodings/idna.py", line 74, in ToASCII  
   label = nameprep(label)  
 File "/usr/lib64/python2.7/encodings/idna.py", line 21, in nameprep  
   newlabel.append(stringprep.map\_table\_b2(c))  
 File "/usr/lib64/python2.7/stringprep.py", line 197, in map\_table\_b2  
   b = unicodedata.normalize("NFKC", al)  
TypeError: normalize() argument 2 must be unicode, not str
```
___
*[`tlsfuzzer/utils/rsa.py` line 84 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemwblxC9e-8Tb0D9g0:-Nf2Nik025VGZ3deMfBU:b-r929v5) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/tlsfuzzer/utils/rsa.py#L84)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

"to represent them"?
</blockquote></details>

fixed to "store"
___
*[`tlsfuzzer/utils/rsa.py` line 168 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NemnN990BDAuVRWBmwd:-Nf2Ns_g9_EtH26xYzNw:b-efyvi6) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/tlsfuzzer/utils/rsa.py#L168)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

why spend a line on that? in general, I think this part can be more compact, `ret[description_doubling_as_comment] = shorter_func_name({0: 1})`
</blockquote></details>

because the code had a lot of duplication before, so it's a leftover from that
___
*[`tlsfuzzer/utils/rsa.py` line 237 at r16](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NempzbgE1tTBaMqL1en:-Nf2PMtk8_62BqnEQNEu:bb7f2mf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/6cc3857f4c63a29639e73bd64ef93efb0c06f4a3/tlsfuzzer/utils/rsa.py#L237)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

That's a `dict(enumerate([0] * 41 + [2]))`
</blockquote></details>

done

**Review by t184256 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, 2 of 2 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17, 1 of 1 files at r18, 1 of 1 files at r19, 1 of 1 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859)* status: all files reviewed, 6 unresolved discussions (waiting on @tomato42)

___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 124 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemio5n-sI5-3qT7I56:-NfBtg6m0FgMi--JefJF:bt0whmy) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7b902fbf62aac6b17fe307ac63caf780b078b2bd/scripts/test-bleichenbacher-timing-marvin.py#L124)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

it is moved to separate module in later patch
</blockquote></details>

yeah, but I still don't see why not have a `n_len = numBytes(priv_key.n)` and use that.
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 215 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NfBvCZE9N3OP0guXqrO:-NfBvCZE9N3OP0guXqrP:b-ux5pmg) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d8d4d586fadc725d251af83c704a86f9aee91543/scripts/test-bleichenbacher-timing-marvin.py#L215)):*
> ```Python
>         ret = {}
> 
>         # first a random well-formed ciphertext canaries
> ```

pluralisation mismatch? s/ a / /
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 779 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NfBx96BEr_l4RQo-2gZ:-NfBx96BEr_l4RQo-2g_:b-i8b0w4) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d44f10d75211360b422ca5d6881216457ff234be/scripts/test-bleichenbacher-timing-marvin.py#L779)):*
> ```Python
>                 for executed, index in enumerate(queries):
>                     if probe_reuse and executed > WARM_UP and \
>                             executed % (len(test_classes) * probe_reuse) == 0:
> ```

This way it can fall into the middle of a test_classes group, while your intention could've been regenerating between such groups.
`(executed - WARM_UP) % (len(test_classes) * probe_reuse) == 0`?
___
*[`tests/verify-scripts-json.py` line 29 at r13](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NfBzX353dVJUvFA5kTX:-NfBzX353dVJUvFA5kTY:b5qjbpm) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a2db8a5d820a2bb4a997ab12ba53d7cf372f0e71/tests/verify-scripts-json.py#L29)):*
> ```Python
>         continue
>     for f in scriptlist:
>         if f not in str(jsonfile) and f[:4] == "test":
> ```

`.startswith()`?

**Review by tomato42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @t184256)

___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 124 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-Nemio5n-sI5-3qT7I56:-NfkZfCm55JlttuTnvvD:bl8tmha) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7b902fbf62aac6b17fe307ac63caf780b078b2bd/scripts/test-bleichenbacher-timing-marvin.py#L124)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

yeah, but I still don't see why not have a `n_len = numBytes(priv_key.n)` and use that.
</blockquote></details>

good point, fixed
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 215 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NfBvCZE9N3OP0guXqrO:-NfkY3Ab4s85wQEHjTPo:b-f7r792) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d8d4d586fadc725d251af83c704a86f9aee91543/scripts/test-bleichenbacher-timing-marvin.py#L215)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

pluralisation mismatch? s/ a / /
</blockquote></details>

right, will fix in subsequent patch
___
*[`scripts/test-bleichenbacher-timing-marvin.py` line 779 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NfBx96BEr_l4RQo-2gZ:-NfkYI2W1HRLiQPUX1nS:bkri5wn) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d44f10d75211360b422ca5d6881216457ff234be/scripts/test-bleichenbacher-timing-marvin.py#L779)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

This way it can fall into the middle of a test_classes group, while your intention could've been regenerating between such groups.
`(executed - WARM_UP) % (len(test_classes) * probe_reuse) == 0`?
</blockquote></details>

no, the WARM_UP is sending the same probe multiple times, not the whole set multiple times; and even if it does fall in the middle, it won't invalidate the results, so: meh
___
*[`tests/verify-scripts-json.py` line 29 at r13](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859#-NfBzX353dVJUvFA5kTX:-NfkYdgHAj4WJ1QFgrAq:b-oopsjf) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a2db8a5d820a2bb4a997ab12ba53d7cf372f0e71/tests/verify-scripts-json.py#L29)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

`.startswith()`?
</blockquote></details>

*sigh* while correct, I think existing code is more readable

**Review by t184256 — APPROVED** [review]
> Reviewed 1 of 1 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tomato42)

**Pull request merged**
