### PR TITLE
support/test Python 3.10

### PR DESCRIPTION
**Pull request by t184256**
Python 3.9 has deprecated, Python 3.10 has removed accessing ABCs
directly from collections. Use collections.abc.Iterable on 3.3+.

### Description

Import `Iterable` from `collections.abc` on supported versions.

Enable Python 3.10 in CI.

### Motivation and Context
Resolves: #766

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

---
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773)* status: all files reviewed, 2 unresolved discussions (waiting on @t184256)

___
*[.github/workflows/ci.yml, line 45 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773#-MhZzdxZ9zhuhGwnx4Ed:-MhZzdxZ9zhuhGwnx4Ee:b-lbizjx) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/35400be9c2aa97838aa31d17a91cc9965ff94033/.github/workflows/ci.yml#L45)):*
> ```YAML
>           - name: py3.10
>             os: ubuntu-latest
>             python-version: 3.10
> ```

I think this will have to be `python-version: '3.10'`, same for the ones below
___
*[tlsfuzzer/expect.py, line 43 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773#-Mh_-Dt55TiCs40myZrX:-Mh_-Dt55TiCs40myZrY:b-dg8vg1) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0e26c883d75e88956dbb7dfcd306b75f94fd4a9c/tlsfuzzer/expect.py#L43)):*
> ```Python
> 
> if sys.version_info >= (3, 3):
>     # pylint: disable=ungrouped-imports,import-error,no-name-in-module
> ```

how about `# pylint: disable=disable-all` or `# pylint: disable=W` ?

**Review by t184256 — COMMENTED** [review]
LGTM complaint is bogus.

> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773#-:-MhnEa6xA_3kEBrlKUPu:bsxuk0)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[.github/workflows/ci.yml, line 45 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773#-MhZzdxZ9zhuhGwnx4Ed:-MhnEiQ5D-wDigz_3ug5:bqjbd2i) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/35400be9c2aa97838aa31d17a91cc9965ff94033/.github/workflows/ci.yml#L45)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I think this will have to be `python-version: '3.10'`, same for the ones below
</blockquote></details>

Used strings.
___
*[tlsfuzzer/expect.py, line 43 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773#-Mh_-Dt55TiCs40myZrX:-MhnErr44MH3RNdgEfs4:b6vpzr7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0e26c883d75e88956dbb7dfcd306b75f94fd4a9c/tlsfuzzer/expect.py#L43)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

how about `# pylint: disable=disable-all` or `# pylint: disable=W` ?
</blockquote></details>

I've figured out a combination that's more narrow. It's frustratingly sensitive to the grouping of the options, but this particular one passes on all current versions, and I hope newer ones will be progressively more robust.

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/773)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @t184256)

**Comment by tomato42** [comment]
Looks good, thanks!

**Pull request merged**
