### PR TITLE
tlsfuzzer/extract.py: Add support for {r,s} tuples in sigs file

### PR DESCRIPTION
**Pull request by GeorgePantelakis**
### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] all new and existing tests pass (see CI results)

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925)

### CODE REVIEW

**Comment by tomato42** [comment]
thinking a bit more: the command line option can also be a `--sig-format [DER|RAW]` instead of a flag, that will be more future proof

**Review by GeorgePantelakis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925)* status: all files reviewed, 5 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/extract.py` line 932 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925#-NxD_6kL11bajUvnunNg:-NxHEMoV47F9OflakDDP:b-yuef6k) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/c33dffd837f199f68448887fe90e40169be98da5/tlsfuzzer/extract.py#L932)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

no, that's a branch that we ought to have test coverage for
</blockquote></details>

Can you elaborate a bit more on why this (and next) path needs to have coverage? I mean it is not tlsfuzzer code and in general, it is a very simple misformating error, perhaps I am missing something.

**Review by tomato42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925)* status: all files reviewed, 5 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/extract.py` line 932 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925#-NxD_6kL11bajUvnunNg:-NxHHUhS3YGXCnILsK-K:b-axpztr) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/c33dffd837f199f68448887fe90e40169be98da5/tlsfuzzer/extract.py#L932)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Can you elaborate a bit more on why this (and next) path needs to have coverage? I mean it is not tlsfuzzer code and in general, it is a very simple misformating error, perhaps I am missing something.
</blockquote></details>

This error will be raised if the user passes in wrong signature file (i.e. in raw format when the system is configured for DER), or the signature file is damaged.

i.e. it's a user facing check and error, therefore we should have test coverage that this kind of mistake is detected and reported appropriately

**Review by tomato42 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925)* status: all files reviewed, 1 unresolved discussion (waiting on @GeorgePantelakis)

**Review by tomato42 — APPROVED** [review]

**Review by tomato42 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/925)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)

**Comment by tomato42** [comment]
looks good, thanks!

**Pull request merged**
