### PR TITLE
More verbose progress

### PR DESCRIPTION
**Pull request by tomato42**
### Description

Allow more verbose progress reporting

### Motivation and Context

UX

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see CI results)
- [x] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
  - n/a
- [x] new and modified scripts were ran against popular TLS implementations:
  - n/a
- [x] required version of tlslite-ng updated in requirements.txt and README.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809)

### CODE REVIEW

**Comment by ueno** [comment]
*[`tests/test_tlsfuzzer_analysis.py` line 486 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-NONVBTi3xB0I1B5p13V:-NONVBTi3xB0I1B5p13W:b-nv2am3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/569af74cb80bbcda310bea78dfd41439f85dbcad/tests/test_tlsfuzzer_analysis.py#L486)):*
> ```Python
>         with mock.patch("tlsfuzzer.analysis.FigureCanvas.print_figure",
>                         mock.Mock()) as mock_save:
>             self.analysis.verbose = True
> ```

Any reason for not doing this in `setUp`?

**Comment by ueno** [comment]
*[`tlsfuzzer/analysis.py` line 270 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-NONVjfxAJD9wYUu6p69:-NONVjfxAJD9wYUu6p6A:b-1hyklt) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/569af74cb80bbcda310bea78dfd41439f85dbcad/tlsfuzzer/analysis.py#L270)):*
> ```Python
>         if self.verbose:
>             start_time = time.time()
>             print("[i] Starting Wilcoxon signed-rank test.")
> ```

nit: the message should or should not end with a period (.)? The others do not seem to have it.

**Review by ueno — DISMISSED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-:-NONWSsGDGVj9twgeb2d:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @tomato42)

**Review by tomato42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809)* status: all files reviewed, 2 unresolved discussions (waiting on @ueno)

___
*[`tests/test_tlsfuzzer_analysis.py` line 486 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-NONVBTi3xB0I1B5p13V:-NOP-5HQ33HEHnSxgk0S:bh68wh9) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/569af74cb80bbcda310bea78dfd41439f85dbcad/tests/test_tlsfuzzer_analysis.py#L486)):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

Any reason for not doing this in `setUp`?
</blockquote></details>

yes, wanted to do it for minimal number of tests, so that both branches (with and without verbose) are covered
___
*[`tlsfuzzer/analysis.py` line 270 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-NONVjfxAJD9wYUu6p69:-NOP-Ufn4UBqYbJr81Uu:b-kxu1fo) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/569af74cb80bbcda310bea78dfd41439f85dbcad/tlsfuzzer/analysis.py#L270)):*
<details><summary><i>Previously, ueno (Daiki Ueno) wrote…</i></summary><blockquote>

nit: the message should or should not end with a period (.)? The others do not seem to have it.
</blockquote></details>

yes, it should be consistent, will fix

**Comment by tomato42** [comment]
@ueno nit fixed, please re-review

**Comment by ueno** [comment]
*[`.github/workflows/ci.yml` line 341 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-NOl_Wnu7jzKx0Qt8Hz-:-NOl_Wnu7jzKx0Qt8Hz0:bb2449e) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/06c0aae69110132d61a418a7cfd0106a11e479fa/.github/workflows/ci.yml#L341)):*
> ```YAML
>           # as http.server uses `sys_version = "Python/" + sys.version.split()[0]`
>           # https://github.com/python/cpython/blob/2c050e52f1ccf5db03819e4ed70690521d67e9fa/Lib/http/server.py#L253
>           if [[ $PYTHON_VERSION == '2.7' || $PYTHON_VERSION == '3.4' || $PYTHON_VERSION == '3.5' || $PYTHON_VERSION == '3.6' || $PYTHON_VERSION == '3.7' || $PYTHON_VERSION == '3.8' || $PYTHON_VERSION == '3.9' ]]; then
> ```

Just a comment: perhaps this could be a little easier to read if you rewrite with `case`?
```shell
case $PYTHON_VERSION in
2.7 | 3.[456789] ) ... ;;
3.10 ) ... ;;
nightly ) ... ;;
*) ...;;
esac
```

**Review by ueno — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/809#-:-NOla7IQCSABtD-NcBA7:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @tomato42)

**Comment by tomato42** [comment]
> Just a comment: perhaps this could be a little easier to read if you rewrite with `case`?

indeed it would be, please check https://github.com/tlsfuzzer/tlsfuzzer/pull/810

**Pull request merged**
