### PR TITLE
Missing 'connect'

### LINKED ISSUE #836: scripts/test-aesccm.py missing connect
Code section:
```
# empty application data message acceptance
    node = conversation
    ext = {}
    if dhe:
        groups = [GroupName.secp256r1,
                  GroupName.ffdhe2048]
        ext[ExtensionType.supported_groups] = SupportedGroupsExtension()\
            .create(groups)
        ext[ExtensionType.signature_algorithms] = \
            SignatureAlgorithmsExtension().create(SIG_ALL)
        ext[ExtensionType.signature_algorithms_cert] = \
            SignatureAlgorithmsCertExtension().create(SIG_ALL)
        ciphers = [CipherSuite.TLS_ECDHE_ECDSA_WITH_AES_128_CCM,
                   CipherSuite.TLS_DHE_RSA_WITH_AES_128_CCM,
                   CipherSuite.TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
    else:
        ext = None
        ciphers = [CipherSuite.TLS_RSA_WITH_AES_128_CCM,
                   CipherSuite.TLS_EMPTY_RENEGOTIATION_INFO_SCSV]
    node = node.add_child(ClientHelloGenerator(ciphers, extensions=ext))
    node = node.add_child(ExpectServerHello())
    node = node.add_child(ExpectCertificate())
    if dhe:
        node = node.add_child(ExpectServerKeyExchange())
    node = node.add_child(ExpectServerHelloDone())
    node = node.add_child(ClientKeyExchangeGenerator())
    node = node.add_child(ChangeCipherSpecGenerator())
    node = node.add_child(FinishedGenerator())
    node = node.add_child(ExpectChangeCipherSpec())
    node = node.add_child(ExpectFinished())
    node = node.add_child(ApplicationDataGenerator(bytearray()))
    node = node.add_child(ApplicationDataGenerator(
        bytearray(b"GET / HTTP/1.0\r\n\r\n")))
    node = node.add_child(ExpectApplicationData())
    node = node.add_child(AlertGenerator(AlertLevel.warning,
                                         AlertDescription.close_notify))
    node = node.add_child(ExpectAlert(AlertLevel.warning,
                                      AlertDescription.close_notify))
    node.next_sibling = ExpectClose()
    conversations["empty app data"] = conversation
```

Is missing:
```
conversation = Connect(host, port)
```

### PR DESCRIPTION
**Pull request by nrathaus**
Add missing 'connect'

fixes #836

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/837)

### CODE REVIEW

**Review by tomato42 — APPROVED** [review]

**Comment by tomato42** [comment]
Please rebase the patch, don't use the merge from master, that option makes the history hard to read

**Comment by nrathaus** [comment]
I am not sure I understand what you mean by 'rebase the patch', do you mean run `git-rebase-patch`?

Or somethng else?

**Comment by tomato42** [comment]
I mean this: [rebase](https://help.github.com/articles/about-git-rebase/) your PR on top of current master branch, then [force push](https://stackoverflow.com/a/10510482/462370) to the same branch as this PR is using.

**Comment by nrathaus** [comment]
I did:
`git rebase --interactive upstream/master`

And then:
`git push -f`

Is this what you meant?

**Comment by tomato42** [comment]
Yes, but you also need to remove the merge patch

**Comment by nrathaus** [comment]
Sorry, but I will need some guidance on how to do it, as I never done that before

Can you look at the PR (per-file-patch as you requested) I opened and see if that is also needed there?

**Comment by tomato42** [comment]
first make sure the `upstream` is up to date:
`git fetch upstream`
then make sure you're on the `missing-connect` branch:
`git checkout missing-connect`
then when doing `git rebase -i upstream/master` remove all lines that referring to my patches (i.e. leave only `Missing 'connect'`)

**Comment by nrathaus** [comment]
Sorry for being a git newbie, but I have done as you said, and now I get:
```
To https://github.com/nrathaus/tlsfuzzer.git
 ! [rejected]        missing-connect -> missing-connect (non-fast-forward)
error: failed to push some refs to 'https://github.com/nrathaus/tlsfuzzer.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

**Comment by tomato42** [comment]
yes, you have to `--force` push the branch after you rebase it

**Review by tomato42 — APPROVED** [review]
I've rebased the branch myself, you don't need to do it now.

> Reviewed 1 of 1 files at r1, 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/837#-:-NcOCRUyBZ4z69VTIqo3:b-4au40f)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nrathaus)

**Comment by tomato42** [comment]
Thanks!

**Pull request merged**
