### PR TITLE
Code Reuse - scripts/test-tls13-certificate-verify.py

### PR DESCRIPTION
**Pull request by nrathaus**
Code reuse to reduce complexity

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/845)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
CI failures are relevant

**Comment by nrathaus** [comment]
1. I tried twice now to merge the comments, but its not really working - do you know how to do it?

2. I don't see the reason for the failure - can you assist? the code seems to do the same (same graph) in the modified and original code

**Comment by nrathaus** [comment]
I accidentally also inserted a minor change to the `printf` that is returned by script_retention it is of course not related to verify

**Comment by tomato42** [comment]
needs rebase to fix merge conflicts

**Comment by nrathaus** [comment]
Done

**Review by tomato42 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/845)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nrathaus)

**Comment by tomato42** [comment]
looks good, thanks

**Pull request merged**
