### PR TITLE
analysis/k_specific: optimize splitting

### PR DESCRIPTION
**Pull request by t184256**
### Description
Here's a series of optimizations that make it go faster;
all but the last one don't change the output.

### Motivation and Context
Splitting measurements.csv into timing.csv
was needlessly slow on my machine.
I thought I can make it go faster. I can.

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tlsfuzzer/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [ ] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [ ] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [ ] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918)

### CODE REVIEW

**Comment by tomato42** [comment]
2.7 failure is relevant:
```
   File "/home/runner/work/tlsfuzzer/tlsfuzzer/tlsfuzzer/analysis.py", line 1916
    yield from zip(out['cmaxk_v'], out['value'], out['k_size'])
             ^
SyntaxError: invalid syntax
```

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918)* status: all files reviewed, 5 unresolved discussions (waiting on @t184256)

___
*[`tlsfuzzer/analysis.py` line 1891 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_6g4a96Om_bHEkX8N:-Nu_6g4a96Om_bHEkX8O:b2h6elh) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1891)):*
> ```Python
>                 # input:
>                 #     rows     0 0 1 1 2 2 2 3 3 3
>                 #     k_sizes  9 8 9 8 9 8 9 8 9 7
> ```

those last three values should be `9 8 7`, a tuple can't start with non-max value
___
*[`tlsfuzzer/analysis.py` line 1906 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_7Uf_CWGUHg6vCwRi:-Nu_7Uf_CWGUHg6vCwRj:b5b6gpz) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1906)):*
> ```Python
>                 row_same = rows.eq(rows.shift(fill_value=previous_row))
> 
>                 cmaxk_vs = values.mask(row_same)
> ```

the `cmaxk_vs` is a bit too terse.... can't figure out what it stands for
___
*[`tlsfuzzer/analysis.py` line 1916 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_7IVc0dczZ-Vx-cWD:-Nu_7IVc0dczZ-Vx-cWE:bewz2tx) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1916)):*
> ```Python
> 
>                 out = chunk.drop(columns="row").assign(cmaxk_v=cmaxk_vs)[mask]
>                 yield from zip(out['cmaxk_v'], out['value'], out['k_size'])
> ```

`yield from` won't work on python 2
___
*[`tlsfuzzer/analysis.py` line 1957 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_9Hz5DwwyMcwLQKNk:-Nu_9Hz5DwwyMcwLQKNl:btjcmw8) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/3b763ca0e56c2cbc161886ba091b14fc1edf3700/tlsfuzzer/analysis.py#L1957)):*
> ```Python
>                             os.makedirs(k_folder_path)
> 
>                             f = open(join(k_folder_path, "timing.csv"), 'wb')
> ```

this can be in a context manager now
___
*[`tlsfuzzer/analysis.py` line 1869 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_ApSH8Si3r6zcTOxR:-Nu_ApSIAf2AmDUJD738:b3e54n) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/8b511ed066145bf6063dff714e6a1809ec66ffd9/tlsfuzzer/analysis.py#L1869)):*
> ```Python
>             chunks = pd.read_csv(
>                 in_fp, iterator=True, chunksize=100000,
>                 dtype=[("row", np.int16), ("k_size", np.int16),
> ```

the row ID definitely needs more than 2 bytes... it should be `np.int64` or even `np.uint64`

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1891 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_6g4a96Om_bHEkX8N:-NucVTpG0zF30BkBFTDO:b-7ql1td) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1891)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

those last three values should be `9 8 7`, a tuple can't start with non-max value
</blockquote></details>

fixed

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1916 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_7IVc0dczZ-Vx-cWD:-NucVWjxBLKtSEoln9tu:bimdr1g) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1916)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`yield from` won't work on python 2
</blockquote></details>

avoided with a plain for...: yield

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1906 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_7Uf_CWGUHg6vCwRi:-NucVb341NstLwiLZzvz:bi4kjju) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1906)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

the `cmaxk_vs` is a bit too terse.... can't figure out what it stands for
</blockquote></details>

expanded slightly =)

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1869 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_ApSH8Si3r6zcTOxR:-NucWPdYDURfQfMbuTln:b5diod5) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/8b511ed066145bf6063dff714e6a1809ec66ffd9/tlsfuzzer/analysis.py#L1869)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

the row ID definitely needs more than 2 bytes... it should be `np.int64` or even `np.uint64`
</blockquote></details>

bumped to uint64, also switched k_size to int16. note that uint32 would realistically be enough for almost-terabyte measurements.csv, so uint64 could possibly be overkill

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1957 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_9Hz5DwwyMcwLQKNk:-NucY4bzARFFiSZCJD9d:b-93ufc0) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/3b763ca0e56c2cbc161886ba091b14fc1edf3700/tlsfuzzer/analysis.py#L1957)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

this can be in a context manager now
</blockquote></details>

wrapped

**Comment by tomato42** [comment]
the PR seems to break the unit tests when analysis dependencies are installed

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918)* status: all files reviewed, 2 unresolved discussions (waiting on @t184256)

___
*[`tlsfuzzer/analysis.py` line 1906 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_7Uf_CWGUHg6vCwRi:-NuyMmYg0oJTZvi9itdS:bwf3nuj) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/77a6a4174fcd1433750496aa0e9f96aef2549917/tlsfuzzer/analysis.py#L1906)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

expanded slightly =)
</blockquote></details>

much better, thanks
___
*[`tlsfuzzer/analysis.py` line 1869 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-Nu_ApSH8Si3r6zcTOxR:-NuyNyJM5sM8qZ0DreEf:b95w9jw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/8b511ed066145bf6063dff714e6a1809ec66ffd9/tlsfuzzer/analysis.py#L1869)):*
<details><summary><i>Previously, t184256 (Alexander Sosedkin) wrote…</i></summary><blockquote>

bumped to uint64, also switched k_size to int16. note that uint32 would realistically be enough for almost-terabyte measurements.csv, so uint64 could possibly be overkill
</blockquote></details>

terabyte `measurements.csv` aren't inconceivable... :> and witch chunked processing we're not really saving much memory by using smaller types
___
*[`tlsfuzzer/analysis.py` line 1928 at r17](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-NuyNgiN1kE1pxxr9j8w:-NuyNgiN1kE1pxxr9j8x:bsgd5r7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0f1f99f36e04c1b0adb97c54448d204e64a16090/tlsfuzzer/analysis.py#L1928)):*
> ```Python
>                 if k_size != max_k_size else
>                 "{0},{0}-sanity\n".format(max_k_size)
>             )
> ```

it's not wrong, but I don't think we gain much readability by using an inline expression here...
___
*[`tlsfuzzer/analysis.py` line 1937 at r17](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-NuyNQkJA2PlbQqmxSiL:-NuyNQkJA2PlbQqmxSiM:b-uw6aw3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0f1f99f36e04c1b0adb97c54448d204e64a16090/tlsfuzzer/analysis.py#L1937)):*
> ```Python
>                 subchunk = subchunk[['curr_maxk_val', 'value']]
>                 subchunk.to_csv(f, header=False, index=False)
>         pipe.close()
> ```

Haven't read the pipe documentation, but this seems to me like something that should be in a `finally:` block...
Feel free to correct me.

**Comment by tomato42** [comment]
To be clear: I consider the inline expression to be a nit, not worth a respin of the PR if the `finally:` block is unnecessary

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1937 at r17](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-NuyNQkJA2PlbQqmxSiL:-Nv61ueb8bA4xdoMSgH5:bua0h62) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0f1f99f36e04c1b0adb97c54448d204e64a16090/tlsfuzzer/analysis.py#L1937)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

Haven't read the pipe documentation, but this seems to me like something that should be in a `finally:` block...
Feel free to correct me.
</blockquote></details>

Wouldn't hurt.

**Comment by t184256** [comment]
*[`tlsfuzzer/analysis.py` line 1928 at r17](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-NuyNgiN1kE1pxxr9j8w:-Nv62DTk6i7hBdvl1g0b:byq10q7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0f1f99f36e04c1b0adb97c54448d204e64a16090/tlsfuzzer/analysis.py#L1928)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

it's not wrong, but I don't think we gain much readability by using an inline expression here...
</blockquote></details>

It is a leftover from previous versions where indentation levels were higher.

**Review by tomato42 — APPROVED** [review]
Could you transplant the https://github.com/tlsfuzzer/python-ecdsa/commit/c56030efe0044c6deb8a5f815eabb590e574fc41 commit to make py2.6 coveralls work again?

> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/918#-:-Nv6SSGGE6JZhkGeGM5v:b-4rdmnx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @t184256)

**Comment by tomato42** [comment]
Thanks!

**Pull request merged**
