### PR TITLE
Improve script retention

### PR DESCRIPTION
**Pull request by nrathaus**
I have modified the `script_retention.py` script to allow running it with just one script instead of all of them

This eases the verification of broken scripts

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/874)

### CODE REVIEW

**Comment by nrathaus** [comment]
I tried to clarify the code, as well as mark the tests that didn't run as SKIP

If you misspell the test name, should it FAIL? I don't know what is your expected outcome from such a thing

**Comment by tomato42** [comment]
> If you misspell the test name, should it FAIL? I don't know what is your expected outcome from such a thing

I think it would be good to error out, with something like "error: script <so-and-so> not found"

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/874)* status: all files reviewed, 4 unresolved discussions (waiting on @nrathaus)

___
*[`tests/scripts_retention.py` line 267 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/874#-Nh2mCXz2wyCii93fAMV:-Nh6VM6w2DhI-J-oOoKc:b-hjuriy) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a2415a86caddc5a2831a11809a9bd1161db0e74e/tests/scripts_retention.py#L267)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why this name? I don't find it particularly descriptive of what it does...
</blockquote></details>

wouldn't `run_only` be better name for it?
___
*[`tests/scripts_retention.py` line 218 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/874#-Nh6VWOVBRP7siB9cby6:-Nh6VWOW1n-KSbNPpuvk:b73giku) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d488952fd99f16eee8187eefa150de8195e77dce/tests/scripts_retention.py#L218)):*
> ```Python
>     """
>     Load a provided config_file, srv_path, expected_size and an optional
>       test_include (which will instruct it what to run and skip the rest)
> ```

how about `(name of the only test script to execute)` instead?
___
*[`tests/scripts_retention.py` line 305 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/874#-Nh6VicL9NqePCKZQ2qZ:-Nh6VicL9NqePCKZQ2q_:b-99sh3c) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d488952fd99f16eee8187eefa150de8195e77dce/tests/scripts_retention.py#L305)):*
> ```Python
>             print(" {0!r}".format(i))
> 
>     if bad > 0:
> ```

and probably add `or good == 0`

**Comment by nrathaus** [comment]
I made the changes you mentioned

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/874)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nrathaus)

**Comment by tomato42** [comment]
looks good, thanks!

**Pull request merged**
