### PR TITLE
Integrating code for minerva analysis

### PR DESCRIPTION
**Pull request by GeorgePantelakis**
This commit integrates the code for Minerva analysis of measurements into the tlsfuzzer/analysis.py. The code uses already existing tests in the Analysis class to analyze the measurements.csv file and create results and graphs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862)* status: all files reviewed, 9 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 76 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecUTCs44kzQHdS_eJq:-NecUTCs44kzQHdS_eJr:b1ltu8x) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L76)):*
> ```Python
>  --status-newline Use newline for printing status line, not carriage return,
>                 works better with output redirection to file.
>  --measurements Specifies that the program will analyze measurement data.
> ```

while indeed that's how we name the output file, I don't think that's the correct way to name the option.

While we could name it `--minerva`, the thing is that the analysis for the ECDHE variant of Raccoon (or FFDHE in TLS 1.3) will work exactly the same: we will capture timing information of server responses where server includes a random component we have no control over, and then we need to sort the results based on bit size of the shared secret.

That being said, we will also want to include Hamming weight tests, and those will have completely different distribution of the classes (there will be no "max k" that is half the measurements) so we will need completely different approach for testing.

So I'm thinking that something like `--bit-size` would be a better name for the option.

The help message would need to explain what kind of analysis it's performing, and that it expects measurements.csv file as input, but I think that name of the option needs to change.
___
*[`tlsfuzzer/analysis.py` line 77 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecX11g86dG7BM3vHQw:-NecX11g86dG7BM3vHQx:bm4zhah) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L77)):*
> ```Python
>                 works better with output redirection to file.
>  --measurements Specifies that the program will analyze measurement data.
>  --skip-sanity  Skip sanity measurements from analysis.
> ```

isn't it only applicable for the bit-size tests?
___
*[`tlsfuzzer/analysis.py` line 94 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecWxcf5ICD3zTsM9ok:-NecWxcf5ICD3zTsM9ol:bp983lg) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L94)):*
> ```Python
>     delay = None
>     carriage_return = None
>     measurements = False
> ```

same here, `bit_size_tests` would be more appropriate
___
*[`tlsfuzzer/analysis.py` line 106 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecX6p29Qfdg0hQ1oIV:-NecX6p29Qfdg0hQ1oIW:b5yq8n7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L106)):*
> ```Python
>                                 "status-delay=",
>                                 "status-newline",
>                                 "measurements",
> ```

as mentioned in help message
___
*[`tlsfuzzer/analysis.py` line 136 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXAh22Yk-PXK1YacU:-NecXAh22Yk-PXK1YacV:b5yq8n7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L136)):*
> ```Python
>         elif opt == "--status-newline":
>             carriage_return = '\n'
>         elif opt == "--measurements":
> ```

as mentioned in help message
___
*[`tlsfuzzer/analysis.py` line 144 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXBst6FaT7PUD-mKu:-NecXBst6FaT7PUD-mKv:b5yq8n7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L144)):*
> ```Python
>         analysis = Analysis(output, ecdf_plot, scatter_plot, conf_int_plot,
>                             multithreaded_graph, verbose, clock_freq, alpha,
>                             workers, delay, carriage_return, measurements,
> ```

as mentioned in help message
___
*[`tlsfuzzer/analysis.py` line 147 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXEHS-jny3n1-Y6X1:-NecXEHS-jny3n1-Y6X2:bi8hhtd) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L147)):*
> ```Python
>                             skip_sanity)
>         if measurements:
>             ret = analysis.analyze_measurements()
> ```

`analyze_bit_sizes`?
___
*[`tlsfuzzer/analysis.py` line 163 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXPjuAyijTxhoQDAY:-NecXPjuAyijTxhoQDAZ:b5yq8n7) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L163)):*
> ```Python
>                  verbose=False, clock_frequency=None, alpha=None,
>                  workers=None, delay=None, carriage_return=None,
>                  measurements=False, skip_sanity=False):
> ```

as mentioned in help message
___
*[`tlsfuzzer/analysis.py` line 1416 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXkeMBISoa8VtaLp8:-NecXkeMBISoa8VtaLp9:b-sqhnev) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L1416)):*
> ```Python
>             yield row
> 
>     def _read_file(self):
> ```

too generic given other analysis types we will want to include

**Review by GeorgePantelakis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 76 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecUTCs44kzQHdS_eJq:-Negs7JZADgUBVKt2HPz:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L76)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

while indeed that's how we name the output file, I don't think that's the correct way to name the option.

While we could name it `--minerva`, the thing is that the analysis for the ECDHE variant of Raccoon (or FFDHE in TLS 1.3) will work exactly the same: we will capture timing information of server responses where server includes a random component we have no control over, and then we need to sort the results based on bit size of the shared secret.

That being said, we will also want to include Hamming weight tests, and those will have completely different distribution of the classes (there will be no "max k" that is half the measurements) so we will need completely different approach for testing.

So I'm thinking that something like `--bit-size` would be a better name for the option.

The help message would need to explain what kind of analysis it's performing, and that it expects measurements.csv file as input, but I think that name of the option needs to change.
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 77 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecX11g86dG7BM3vHQw:-NegjVc51seOQCQtkT1O:b8r4fki) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L77)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

isn't it only applicable for the bit-size tests?
</blockquote></details>

I think that in every test that would do some kind of sanity we can implement some logic to skip it. So it could be applicable to hamming weight later and not only to bit-size tests.
___
*[`tlsfuzzer/analysis.py` line 94 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecWxcf5ICD3zTsM9ok:-Negs8Uk9Sv0o8YPBVwb:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L94)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same here, `bit_size_tests` would be more appropriate
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 106 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecX6p29Qfdg0hQ1oIV:-Negs9Mo2uu5vda2eN-K:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L106)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

as mentioned in help message
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 136 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXAh22Yk-PXK1YacU:-Negs9nPE-D5j3MU1mw5:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L136)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

as mentioned in help message
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 144 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXBst6FaT7PUD-mKu:-NegsAGPANC0YRtSzLrm:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L144)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

as mentioned in help message
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 147 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXEHS-jny3n1-Y6X1:-NegsB186Ind7jq7DU6f:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L147)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

`analyze_bit_sizes`?
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 163 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXPjuAyijTxhoQDAY:-NegsBdN7Z8E2RQCYg7X:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L163)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

as mentioned in help message
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1416 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecXkeMBISoa8VtaLp8:-NegsC_s9VJtLxCZy-l-:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L1416)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

too generic given other analysis types we will want to include
</blockquote></details>

Done.

**Review by tomato42 — DISMISSED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862)* status: all files reviewed, 2 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 77 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NecX11g86dG7BM3vHQw:-NehVd4S3DwwKLlksq0G:b-ak0gpo) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/ed494cc3660a088d92f01d6c334f0275f0b5f18c/tlsfuzzer/analysis.py#L77)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

I think that in every test that would do some kind of sanity we can implement some logic to skip it. So it could be applicable to hamming weight later and not only to bit-size tests.
</blockquote></details>

while true, I don't see utility of not doing sanity checks if they're possible to do: it's minimal extra calculation, and it's a generally recommended practice. ok, we can leave that as-is
___
*[`tlsfuzzer/analysis.py` line 1522 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NehWCSg3Qeboz2Z6uxK:-NehWCSh-e4QHWdB0DCX:bfzgwo6) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/47ffe8179b135a2156ab5de64decf7ef97f3bcd6/tlsfuzzer/analysis.py#L1522)):*
> ```Python
>     def conf_plot_for_all_k(self, k_sizes):
>         """
>         Creates a confindence interval plot that includes all the K bit-sizes
> ```

nit: s/confindence/confidence/
___
*[`tlsfuzzer/analysis.py` line 1595 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NehWN4FD0i3Yc_ByIvk:-NehWN4FD0i3Yc_ByIvl:bzc5n6q) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/47ffe8179b135a2156ab5de64decf7ef97f3bcd6/tlsfuzzer/analysis.py#L1595)):*
> ```Python
>         which are placed in an analysis_results directory in the output folder.
> 
>         Tests: Sign test, paired t-test, wilcoxon test and bootstrap test.
> ```

bootstrap isn't a test, it's a mechanism to calculate the confidence intervals

**Review by GeorgePantelakis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862)* status: all files reviewed, 1 unresolved discussion (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 1595 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862#-NehWN4FD0i3Yc_ByIvk:-NehXUZn8c6QM-HlJCHW:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/47ffe8179b135a2156ab5de64decf7ef97f3bcd6/tlsfuzzer/analysis.py#L1595)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

bootstrap isn't a test, it's a mechanism to calculate the confidence intervals
</blockquote></details>

Done.

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/862)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)

**Pull request merged**
