### PR TITLE
Some cleanup and __repr__ adds

### PR DESCRIPTION
**Pull request by nrathaus**
Hi,

1. I fixed many of the scripts to remove unused imports
2. I added __repr__ in messages, expect - I might have missed some
3. I made the __repr__ generic and receive a list of attributes to dump, it also cascades into the child (should we look not next_sibling as well?)

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821)* status: 2 of 53 files reviewed, 15 unresolved discussions (waiting on @nrathaus)

*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKQpw91nrfNdxzt2lM:-NXKQpw91nrfNdxzt2lN:bcisbq) (no related file):*
Some patches use an email associated with your account, while others do not, please make it consistent (change author email or add the other email to your account)

___
*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKTTn77pH1uIqTgkfj:-NXKTTn77pH1uIqTgkfk:b-9jcwy0) (no related file):*
those are issues in multiple patches, so I won't list them in every:
1. I don't like the `if ... continue` construction for parsing, it's overly verbose when the body of the if is just a singly line
2. nit: there are a lot of lines which contain just spaces
3. why `self.__getattribute__` instead of `getattr(self, 'name')`?
4. test coverage around repr changes missing

___
*[a discussion](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKWYdv9IwTGSUoEJYn:-NXKWYdv9IwTGSUoEJYo:b-uz5id7) (no related file):*
this feels to me like two completely unrelated changes: one around repr handling and printing, and the other the cleanup and removal of unused imports, please split

___
___
*[`scripts/test-aes-gcm-nonces.py` line 50 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKRJiS5Vk8c67Ecc5W:-NXKRJiS5Vk8c67Ecc5X:b-e5eceu) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aes-gcm-nonces.py#L50)):*
> ```Python
>     print(" --help         this message")
> 
> def return_tests(host, port):
> ```

can you explain the rationale for doing this?
___
*[`scripts/test-aes-gcm-nonces.py` line 146 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKRTge3XSNyXhqjXlr:-NXKRTge3XSNyXhqjXls:blgq18f) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aes-gcm-nonces.py#L146)):*
> ```Python
>         if opt == '-j':
>             json_filename = arg
>             continue
> ```

I very much don't like this style of argument parsing, it's overly verbose
___
*[`scripts/test-aes-gcm-nonces.py` line 178 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKReEYD7PLej519-BS:-NXKReEZC-xgzMvw-T9F:b1c2y87) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aes-gcm-nonces.py#L178)):*
> ```Python
>             help_msg()
>             sys.exit(0)
>         
> ```

nit: spaces
___
*[`scripts/test-aes-gcm-nonces.py` line 241 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKRlgh3YJ3SZMNVRvb:-NXKRlgh3YJ3SZMNVRvc:bcaq1vs) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aes-gcm-nonces.py#L241)):*
> ```Python
>                 xpass += 1
>                 outcome['xpassed'].append(c_name)
>                 xpassed.append(c_name)
> ```

doesn't `outcome['xpassed']` completely duplicate the `xpassed`?
___
*[`scripts/test-aes-gcm-nonces.py` line 248 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKRvqaD_y-9MD8SaTY:-NXKRvqaD_y-9MD8SaTZ:b-nxxhv) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aes-gcm-nonces.py#L248)):*
> ```Python
>                         bad += 1
>                         outcome['failed'].append(c_name)
>                         failed.append(c_name)
> ```

same here, looks to me like duplication
___
*[`scripts/test-aes-gcm-nonces.py` line 257 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKSGwC1VP-bUI5nb2n:-NXKSGwC1VP-bUI5nb2o:b-s10v92) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aes-gcm-nonces.py#L257)):*
> ```Python
>         else:
>             if res:
>                 outcome['good'].append(c_name)
> ```

`good` and `bad` are just internal, why we're exposing them externally? why the stuff in summary: https://tlsfuzzer.readthedocs.io/en/latest/failure-analysis.html#execution-summary is insufficient?
___
*[`scripts/test-aesccm.py` line 67 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKSiQkEdtiF-eh_UAn:-NXKSiQkEdtiF-eh_UAo:br9gl5h) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aesccm.py#L67)):*
> ```Python
>         if opt == '-h':
>             host = arg
>             continue
> ```

again, don't like it
___
*[`scripts/test-aesccm.py` line 99 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKSkxn3859kTy7HfAp:-NXKSkxn3859kTy7HfAq:b1c2y87) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-aesccm.py#L99)):*
> ```Python
>             help_msg()
>             sys.exit(0)
>         
> ```

nit: spaces
___
*[`scripts/test-bleichenbacher-timing.py` line 126 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKTJBB7dVZynQCnE0S:-NXKTJBB7dVZynQCnE0T:b-yoskw5) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-bleichenbacher-timing.py#L126)):*
> ```Python
>     try:
>         runner.run()
>     except Exception as _:
> ```

why not just `except Exception:`?
___
*[`scripts/test-bleichenbacher-timing.py` line 872 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKTOsFCcFVNwVtLXrK:-NXKTOsFCcFVNwVtLXrL:b1c2y87) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/scripts/test-bleichenbacher-timing.py#L872)):*
> ```Python
>                                 "cpu-list=",
>                                 "static-enc"])
>     
> ```

nit: spaces
___
*[`tlsfuzzer/expect.py` line 73 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKU1jFDp87psfbo3_y:-NXKU1jFDp87psfbo3_z:b-vwhrlg) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/tlsfuzzer/expect.py#L73)):*
> ```Python
>         
>         if self.child:
>             cmd += f"{self.child}"
> ```

not python 2.6 compatible
___
*[`tlsfuzzer/tree.py` line 66 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/821#-NXKW9fR82T2U93DetY1:-NXKW9fR82T2U93DetY2:bq572in) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7651e76a72843e86ab6baefd08778e5d5d8661cd/tlsfuzzer/tree.py#L66)):*
> ```Python
>             will be included in the text representation
>         """
>         return "{0}({1})\n".format(
> ```

I'm pretty sure it's not pythonic to have newlines in  `repr()` output...

**Comment by nrathaus** [comment]
I reverted all the `continue` to `elif` - I think reading wise, continue is more clear and less error prone, but its your project to decide

**Comment by nrathaus** [comment]
Regarding `outcome`, I wasn't 100% which one we would need and which one we won't so, I made an object with everything inside it, which then can be passed to a function that creates the Junit and would spit only the needed parts

**Comment by nrathaus** [comment]
I removed all the `cmd += f"{self.child}"`

**Comment by tomato42** [comment]
> Hi,
> 
> By moving all the tests to a generic function called`return_tests` - we can have a python file call a Module/stub that calls this function and does everything - at the moment you have the same code written multiple times with a few exceptions

but that's the problem, there are always slight differences, changes to configuration, different command line options, etc. so it won't be possible to just take an arbitrary test script and just call `return_tests()`, you need to know what arguments it accepts. And while there are some command line options that apply to majority of scripts, there are even more ones that are relevant to one and only one script.

yes, I'd prefer to have something generic, but between `scripts/test-dhe-no-shared-secret-padding.py`, `scripts/test-bleichenbacher-timing.py`, and the regular `scripts/test-conversation.py`, I think any mechanism would have to be rather complex...

> Regarding `outcome`, I wasn't 100% which one we would need and which one we won't so, I made an object with everything inside it, which then can be passed to a function that creates the Junit and would spit only the needed parts

they're needed only to print the summary and have correct exit code for the script, as long as that happens, it's good

**Pull request closed without merging**
