### PR TITLE
ECDH support && removed bit_recognition_size from extract

### PR DESCRIPTION
**Pull request by GeorgePantelakis**
### Description
1) removed unused bit_recognition_size variable from extract.py and updated the test coverage
2) created the --ecdh flag in extract.py that will enable support for ECDH secret extraction.

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments
- [ ] all new and existing tests pass (see CI results)

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954)* status: all files reviewed, 3 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/extract.py` line 84 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O5TWZkhBSW7694itrr8:-O5TWZkhBSW7694itrr9:b60fvh4) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/61f45d9701294fd87ef92d2a7e3dfb076653a562/tlsfuzzer/extract.py#L84)):*
> ```Python
>     print(" --sig-format [DER|RAW] Specifies the format of the signatures in")
>     print("                the binary file, 'DER' or 'RAW'. Default DER.")
>     print(" --priv-key-ecdsa FILE Read the ecdsa private key from PEM file.")
> ```

not a fan of renaming user-facing command line arguments...
if you really want to do it, we should retain support for the `-ecdsa` variant, so that it doesn't break existing scripts/setups that use this code...
___
*[`tlsfuzzer/extract.py` line 251 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O5TYHcQAVGz97aRmOGA:-O5TYHcQAVGz97aRmOGB:b7e6mr0) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d4ff9cde3fb5da492dba256298e01f4ef4258ce7/tlsfuzzer/extract.py#L251)):*
> ```Python
> 
>     if ecdh \
>        and not all([sigs, priv_key, raw_times, data]):
> ```

I find the re-use of `sigs` for ecdh much more confusing than the use of "ecdsa" to refer to a private ecdh key...

and we really should explain what are the meaning and what are the necessary values for the ecdh extraction in the help message and in the docs
___
*[`tlsfuzzer/extract.py` line 1159 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O5TXDKvDpm9-74z3WaA:-O5TXDKvDpm9-74z3WaB:bjlcqol) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/d4ff9cde3fb5da492dba256298e01f4ef4258ce7/tlsfuzzer/extract.py#L1159)):*
> ```Python
>         """
>         return int(np.ceil(
>             ecdsa.util.bit_length(self.priv_key.curve.curve._CurveFp__p) / 8))
> ```

this should call `.p()` instead, also "round-up" for integers should be implemented using integers:
`(bit_length(p()) + 7) / 8`

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954)* status: all files reviewed, 3 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/extract.py` line 77 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O8h6HhV-wKa6YMfa0i3:-O8h6HhV-wKa6YMfa0i4:b-4m6gxl) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0396ab0a1bce3e655d9b78526527f5061d72cc98/tlsfuzzer/extract.py#L77)):*
> ```Python
>     print(" --raw-data FILE Read the data used for signing from an external")
>     print("                file. The file must be in binary format.")
>     print(" --data-size num The size of each data used for gathering.")
> ```

"gathering"?
___
*[`tlsfuzzer/extract.py` line 354 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O8h6yJZ7Y2OwzZhmK_G:-O8h6yJZ7Y2OwzZhmK_H:bs0rnj1) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0396ab0a1bce3e655d9b78526527f5061d72cc98/tlsfuzzer/extract.py#L354)):*
> ```Python
>         :param int port: TLS server port
>         :param str data: Name of file with data used for signing
>         :param int data_size: Size of each data used for gathering
> ```

gathering?
___
*[`tlsfuzzer/extract.py` line 359 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O8h729oD1qhsRYeBD5F:-O8h729oD1qhsRYeBD5G:b-j197rt) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0396ab0a1bce3e655d9b78526527f5061d72cc98/tlsfuzzer/extract.py#L359)):*
> ```Python
>             formats are supported
>         :param str values: Name of file with the values
>         :param int values_size: Size of each valuesinterpretations
> ```

space missing

**Review by GeorgePantelakis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/extract.py` line 77 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O8h6HhV-wKa6YMfa0i3:-O8kkog-CWD2LWa8Rc7i:bu8nt4j) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0396ab0a1bce3e655d9b78526527f5061d72cc98/tlsfuzzer/extract.py#L77)):*
<details><summary><i>Previously, tomato42 (Alicja Kario) wrote…</i></summary><blockquote>

"gathering"?
</blockquote></details>

I think processing might be better. 
___
*[`tlsfuzzer/extract.py` line 354 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O8h6yJZ7Y2OwzZhmK_G:-O8kkvXHELze9UPWuGIy:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0396ab0a1bce3e655d9b78526527f5061d72cc98/tlsfuzzer/extract.py#L354)):*
<details><summary><i>Previously, tomato42 (Alicja Kario) wrote…</i></summary><blockquote>

gathering?
</blockquote></details>

Done.
___
*[`tlsfuzzer/extract.py` line 359 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954#-O8h729oD1qhsRYeBD5F:-O8kkvkP5FvA_rCOImGj:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/0396ab0a1bce3e655d9b78526527f5061d72cc98/tlsfuzzer/extract.py#L359)):*
<details><summary><i>Previously, tomato42 (Alicja Kario) wrote…</i></summary><blockquote>

space missing
</blockquote></details>

Done.

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/954)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)

**Comment by tomato42** [comment]
looks good, thanks!

**Pull request merged**
