### PR TITLE
tlsfuzzer/analysis.py: implementation of smart analysis

### PR DESCRIPTION
**Pull request by GeorgePantelakis**
### Description
Smart analysis is a feature in the bit size analysis. It tries to figure out how many samples are needed to achieve the desired CI level and then it analyzes only these samples rather than the whole data (if smaller).

### Motivation and Context
This PR was inspired by [issue#901](https://github.com/tlsfuzzer/tlsfuzzer/issues/901)

### Checklist
- [ ] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] all new and existing tests pass (see CI results)

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913)* status: all files reviewed, 9 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFHdSz--LMiKn80Kwq):*
"implementation of smart analysis"?
___
*[`tlsfuzzer/analysis.py` line 81 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFIUH16cP99kbW5y7f:-NsFIUH16cP99kbW5y7g:b-mbgkq6) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L81)):*
> ```Python
>                    is expected as input and it should be in long-format
>                    ("row id,column id,value").
>  --no-smart-analysis By default the script will compute how much data are
> ```

"...when analysing bit size..."?
___
*[`tlsfuzzer/analysis.py` line 86 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFJHVmAyBcG9aAKgcn:-NsFJHVmAyBcG9aAKgco:b-37wgpb) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L86)):*
> ```Python
>                    This option disables this feature and uses all the available
>                    data.
>  --bit-size-desire-ci num The desired amount of ns (or lower) that the CIs
> ```

I think we can spare a single letter and call it `--bit-size-desired-ci`...
___
*[`tlsfuzzer/analysis.py` line 89 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFIhuk5LW6hZEw68dE:-NsFIhuk5LW6hZEw68dF:b-oo7cex) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L89)):*
> ```Python
>                    should have after the analysis up to recall size option.
>                    Used only with smart analysis. Default 1 ns.
>  --bit-recall-size num The <num> bigger bit size will be used to determine how
> ```

s/bigger/biggest/?

Also, not a fan of the "recall" name, here and in variable names
___
*[`tlsfuzzer/analysis.py` line 1609 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFJhVHE1yJJwOeNKyv:-NsFJhVHE1yJJwOeNKyw:b-lap13s) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L1609)):*
> ```Python
>                     print("[i] Skillings-Mack test done in {:.3}s".format(
>                         time.time() - start_time))
>                     print("[i] Skillings-Mack pvalue: {0:.6e}".format(
> ```

s/pvalue/p-value/
___
*[`tlsfuzzer/analysis.py` line 2031 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFKJGz20QMLAOcRQ34:-NsFKJGz20QMLAOcRQ35:b-2ox5wn) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L2031)):*
> ```Python
> 
>         if self.bit_size_recall_size > len(k_sizes):
>             self.bit_size_recall_size = 4 if len(k_sizes) > 4 else len(k_sizes)
> ```

wouldn't it be better to just `self.bit_size_recall_size = len(k_sizes)`?
___
*[`tlsfuzzer/analysis.py` line 2043 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFKcDz8W5R1KmPbiOn:-NsFKcDz8W5R1KmPbiOo:bi5nwat) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L2043)):*
> ```Python
>             for method in recall_results
>         ]
>         smaller_recall_ci = min(filter(lambda x: x > 0, all_recall_cis))
> ```

no need for `filter()`, `min(i for i in all_recall_cis if i > 0)` will do
___
*[`tlsfuzzer/analysis.py` line 2044 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFL8OiELpO4oM1DvqR:-NsFL8OiELpO4oM1DvqS:b6qdb8t) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L2044)):*
> ```Python
>         ]
>         smaller_recall_ci = min(filter(lambda x: x > 0, all_recall_cis))
>         magnitude_diff = np.ceil(smaller_recall_ci / self.bit_size_desire_ci)
> ```

I don't see a need for `ceil()` here
___
*[`tlsfuzzer/analysis.py` line 2046 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFLLCm95wHwrtvJd-0:-NsFLLCm95wHwrtvJd-1:bx6omeu) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L2046)):*
> ```Python
>         magnitude_diff = np.ceil(smaller_recall_ci / self.bit_size_desire_ci)
>         self._bit_size_data_limit = int(
>             np.square(magnitude_diff) * self._bit_size_data_used
> ```

why `np.square()`?  why not `magnitude_diff ** 2` ?

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913)* status: all files reviewed, 2 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 2031 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsJAgakAN1BsCcYNNhJ:-NsJAgakAN1BsCcYNNhK:b-ijjxo9) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/192df4df709ce992868b51bbb3b8e6fc6bed4ffc/tlsfuzzer/analysis.py#L2031)):*
> ```Python
> 
>         if self.bit_size_recall_size > len(k_sizes):
>             self.bit_size_recall_size = min(len(k_sizes), 4)
> ```

I don't understand the logic here: the user asked for more groups to be analysed, we notice that the number of groups to analyse is larger than the number of groups we have, so instead of limiting it to the number of groups we have, we limit it to 4. And we do it silently, without writing any warning messages... As a user I would say that's unexpected.

**Review by GeorgePantelakis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913)* status: all files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 89 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsFIhuk5LW6hZEw68dE:-NsN9JCw58KEnv97IsQn:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/2219bca962ac3c7fa41901e60c2855729a38004f/tlsfuzzer/analysis.py#L89)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

s/bigger/biggest/?

Also, not a fan of the "recall" name, here and in variable names
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 2031 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsJAgakAN1BsCcYNNhJ:-NsNBffQ6GJpd0GFiAAO:b-dvdtit) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/192df4df709ce992868b51bbb3b8e6fc6bed4ffc/tlsfuzzer/analysis.py#L2031)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I don't understand the logic here: the user asked for more groups to be analysed, we notice that the number of groups to analyse is larger than the number of groups we have, so instead of limiting it to the number of groups we have, we limit it to 4. And we do it silently, without writing any warning messages... As a user I would say that's unexpected.
</blockquote></details>

Yes, you are right, I had something different on my mind but after some thought it is better to have it be just len(k_sizes).

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913)* status: all files reviewed, 2 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 89 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsOgUBfB7nsJFOdhhHb:-NsOgUBfB7nsJFOdhhHc:bxohw2y) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/525e6f7743902345617de79279ca058f49ec85e7/tlsfuzzer/analysis.py#L89)):*
> ```Python
>                    should have after the analysis up to recognition size
>                    option. Used only with smart analysis. Default 1 ns.
>  --bit-recognition-size num The <num> bigger bit size will be used to determine
> ```

s/bigger/biggest/
___
*[`tlsfuzzer/analysis.py` line 2031 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913#-NsOgk_J6Q520B8wN92w:-NsOgk_J6Q520B8wN92x:b-r8vg8t) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/525e6f7743902345617de79279ca058f49ec85e7/tlsfuzzer/analysis.py#L2031)):*
> ```Python
> 
>         if self.bit_recognition_size > len(k_sizes):
>             self.bit_recognition_size = len(k_sizes) - 1
> ```

hmm, still not sure if it's correct... consider this:
initial bit_recognition_size = 4, len(k_sizes) = 4, resulting bit_recognition_size = 4
initial bit_recognition_size = 5, len(k_sizes) = 4, resulting bit_recognition_size = 3

IMHO it should either be `>=` instead of `>`, or we should drop the `- 1`

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/913)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)

**Comment by tomato42** [comment]
thanks!

**Pull request merged**
