### PR TITLE
Improvements in performace on tlsfuzzer/analysis.py 

### PR DESCRIPTION
**Pull request by GeorgePantelakis**
* add --measurements flag
* Add threads to creation of nonce size dirs that speed things up
* smarter way to check if t-test shoulb be run
* add progress report to bit size dir creation

### Motivation and Context
This PR was inspired by [issue#901](https://github.com/tlsfuzzer/tlsfuzzer/issues/901)

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] the changes are also reflected in documentation and code comments

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908)* status: all files reviewed, 8 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tests/test_tlsfuzzer_analysis.py` line 1352 at r3](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbXqBOCfetUABE4rF2:-NqbXqBOCfetUABE4rF3:b-k0wfzv) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/9253c86b11b3866617ecaf84e67d8a445f7668e1/tests/test_tlsfuzzer_analysis.py#L1352)):*
> ```Python
>         ret_value = self.analysis._check_data_for_rel_t_test()
> 
>         self.assertEqual(ret_value, True)
> ```

nit: EOL missing at end of file
___
*[`tlsfuzzer/analysis.py` line 1515 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbV0WZ4o6Rwitbhvs_:-NqbV0W_9YWGxYdboDNt:b-dnovp4) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1515)):*
> ```Python
>     def _k_size_writer(self, k_size, k_queue, max_k_size):
>         data_buffer = []
>         buffer_size = 5
> ```

that feels rather small to me... I'd say it's better to write at least few kilobytes at a time, if possible (I mean, modern storage can't write less than 4KiB at a time...)
___
*[`tlsfuzzer/analysis.py` line 1538 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbUfwi0mcAqoF3IWer:-NqbUfwi0mcAqoF3IWes:b-5ybnk5) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1538)):*
> ```Python
> 
>                 if len(data_buffer) >= buffer_size:
>                     data_buffer = list(map(
> ```

why `list(map(`? this is used just once: to feed to `"\n".join(`, and that this accepts an iterator, which means we don't need to create the list...
___
*[`tlsfuzzer/analysis.py` line 1548 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbVJKc1qk1dkVBaH2_:-NqbVJKc1qk1dkVBaH2a:b3k419l) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1548)):*
> ```Python
>             if len(data_buffer) > 0:
>                 data_buffer = list(map(
>                     lambda data: "{0},{1}".format(data[0], data[1]),
> ```

same as above, I think simple iterator would be more efficient here
___
*[`tlsfuzzer/analysis.py` line 1576 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbWdXI4nkR0vRTerVg:-NqbWdXI4nkR0vRTerVh:b-unfcg2) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1576)):*
> ```Python
>                 k_proccess = Thread(target=self._k_size_writer,
>                                     args=(k_size, k_queue, max_k_size,))
>                 k_proccess.start()
> ```

the whole `for data in data_iter` should be inside `try: ... finally:...` block and the shutdown of the worker threads should be in the `finally:`. That's necessary so that the processes are correctly cleaned up if somebody cancels it with ^C
___
*[`tlsfuzzer/analysis.py` line 1508 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbZ0SD-2TiHZWfUHP2:-NqbZ0SD-2TiHZWfUHP3:b-22rxvs) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6f2aaf4c350f899d69c4de4194cdfaa66446951/tlsfuzzer/analysis.py#L1508)):*
> ```Python
> 
>                 if status:
>                     status[0] += sum([len(x) for x in row], 3)
> ```

wouldn't `status[0] = f.tell()` be much easier?
___
*[`tlsfuzzer/analysis.py` line 1576 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbZ8S88nrcxdU2xZOy:-NqbZ8S88nrcxdU2xZOz:b-hw0hhv) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6f2aaf4c350f899d69c4de4194cdfaa66446951/tlsfuzzer/analysis.py#L1576)):*
> ```Python
>                 total_size = os.path.getsize(
>                     join(self.output, self.measurements_filename)
>                 )
> ```

to make `.tell()` work, doing `.seek(0, 2), tell(), seek(0)` to get the length of the file? (even inside the thread)
___
*[`tlsfuzzer/analysis.py` line 1607 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbZbFV2b67_uzpDKRy:-NqbZbFV2b67_uzpDKRz:bcly66u) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6f2aaf4c350f899d69c4de4194cdfaa66446951/tlsfuzzer/analysis.py#L1607)):*
> ```Python
>         if status:
>             status[2].set()
>             progress.join()
> ```

for this to work correctly, it should be in the `finally:...` block

**Comment by tomato42** [comment]
test coverage for verbose bit analysis missing

**Review by GeorgePantelakis — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-:-NqcBe7M0S4ESnX53Uxe:b-896fix)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @tomato42)

___
*[`tlsfuzzer/analysis.py` line 1515 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbV0WZ4o6Rwitbhvs_:-Nqc4BXM7KEirFFxihAw:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1515)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

that feels rather small to me... I'd say it's better to write at least few kilobytes at a time, if possible (I mean, modern storage can't write less than 4KiB at a time...)
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1538 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbUfwi0mcAqoF3IWer:-Nqc3tEt1HaJdFdMwZio:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1538)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

why `list(map(`? this is used just once: to feed to `"\n".join(`, and that this accepts an iterator, which means we don't need to create the list...
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1548 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbVJKc1qk1dkVBaH2_:-Nqc3tqm5CiZ8q-Lhg7W:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1548)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

same as above, I think simple iterator would be more efficient here
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1576 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbWdXI4nkR0vRTerVg:-Nqc3w_m8nUqDSBbYtGH:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1576)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

the whole `for data in data_iter` should be inside `try: ... finally:...` block and the shutdown of the worker threads should be in the `finally:`. That's necessary so that the processes are correctly cleaned up if somebody cancels it with ^C
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1508 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbZ0SD-2TiHZWfUHP2:-Nqc3s3L5GiKIdrueyTD:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6f2aaf4c350f899d69c4de4194cdfaa66446951/tlsfuzzer/analysis.py#L1508)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

wouldn't `status[0] = f.tell()` be much easier?
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1576 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbZ8S88nrcxdU2xZOy:-Nqc5Dt19iIyB7PVJwGG:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6f2aaf4c350f899d69c4de4194cdfaa66446951/tlsfuzzer/analysis.py#L1576)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

to make `.tell()` work, doing `.seek(0, 2), tell(), seek(0)` to get the length of the file? (even inside the thread)
</blockquote></details>

Done.
___
*[`tlsfuzzer/analysis.py` line 1607 at r4](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbZbFV2b67_uzpDKRy:-Nqc3wt_-e_TUP6BZg_y:b-896fix) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a6f2aaf4c350f899d69c4de4194cdfaa66446951/tlsfuzzer/analysis.py#L1607)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

for this to work correctly, it should be in the `finally:...` block
</blockquote></details>

Done.

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 1548 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqbVJKc1qk1dkVBaH2_:-NqcJxSsDokmiA-jBz4t:b2dhfye) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/7ca7e2d07858cb3ee4821ebaeb63924d354caf39/tlsfuzzer/analysis.py#L1548)):*
<details><summary><i>Previously, GeorgePantelakis (George Pantelakis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

this still is using `map()`
___
*[`tlsfuzzer/analysis.py` line 1575 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqcK1XV84JGODO9BEOs:-NqcK1XV84JGODO9BEOt:bazlmut) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/cb9017d785893bb4a904e7655806ef28aa2b5194/tlsfuzzer/analysis.py#L1575)):*
> ```Python
>         if self.verbose:
>             try:
>                 status = [0, 0, Event()]
> ```

if the position is in bytes, then `getsize()` here is correct...
___
*[`tlsfuzzer/analysis.py` line 1556 at r7](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-NqcKqqQ5OBzm5f5fDc6:-NqcKqqQ5OBzm5f5fDc7:byd1ayt) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/08dd80e858dae1a2211200795e969181e1115035/tlsfuzzer/analysis.py#L1556)):*
> ```Python
> 
>             if len(data_buffer) > 0:
>                 data_string = "\n".join([
> ```

`[` `]` are not needed here

**Review by tomato42 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/908#-:-NqhpgeN2geNn3x-Q8b8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)

**Pull request merged**
