### PR TITLE
certificate-verify: allow setting the cipher to use

### PR DESCRIPTION
**Pull request by tomato42**
### Description

allow setting the cipher to be used for connection, makes it possible to run against servers that have CBC mode disabled

### Motivation and Context

relates to #563

### Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tomato42/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [ ] the changes are also reflected in documentation and code comments
- [x] all new and existing tests pass (see CI results)
- [ ] [test script checklist](https://github.com/tomato42/tlsfuzzer/wiki/Test-script-checklist) was followed for new scripts
- [x] new test script added to `tlslite-ng.json` and `tlslite-ng-random-subset.json`
- [x] new and modified scripts were ran against popular TLS implementations:
  - [ ] OpenSSL
  - [x] NSS
  - [ ] GnuTLS
- [ ] required version of tlslite-ng updated in requirements.txt and README.md

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801)

### CODE REVIEW

**Review by ep69 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @tomato42)

___
*[`scripts/test-certificate-verify.py` line 56 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801#-NBC6pMB8XcXGvdQKQnw:-NBC6pMB8XcXGvdQKQnx:b1dwwxm) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/e514a41ea5b03f3abe93b418ea87930b1604a286/scripts/test-certificate-verify.py#L56)):*
> ```Python
>     print(" -c file.pem    file with certificate for client")
>     print(" -d             negotiate (EC)DHE instead of RSA key exchange")
>     print(" -C ciph        Use specified ciphersuite. Either numerical value or")
> ```

I am confused a bit, https://github.com/tlsfuzzer/tlsfuzzer/issues/563 sounds like we want to use `-d` argument..?
___
*[`scripts/test-certificate-verify.py` line 99 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801#-NBC5w39Cp-U9ZVxe-l6:-NBC5w39Cp-U9ZVxe-l7:b6dvml3) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/e514a41ea5b03f3abe93b418ea87930b1604a286/scripts/test-certificate-verify.py#L99)):*
> ```Python
>             else:
>                 try:
>                     ciphers = [getattr(CipherSuite, arg)]
> ```

Could we simplify the whole `try ... except` block by using default value in getattr? Something like:`ciphers = [getattr(CipherSuite, arg, int(arg))]`

**Review by tomato42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ep69 and @tomato42)

___
*[`scripts/test-certificate-verify.py` line 56 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801#-NBC6pMB8XcXGvdQKQnw:-NBCmZRrA93jSk4k3eL-:b-9ellv) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/e514a41ea5b03f3abe93b418ea87930b1604a286/scripts/test-certificate-verify.py#L56)):*
<details><summary><i>Previously, ep69 (Stanislav Židek) wrote…</i></summary><blockquote>

I am confused a bit, https://github.com/tlsfuzzer/tlsfuzzer/issues/563 sounds like we want to use `-d` argument..?
</blockquote></details>

`-d` is not sufficient for implementations that support only GCM ciphers; I've updated #563 to be more explicit about it
___
*[`scripts/test-certificate-verify.py` line 99 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801#-NBC5w39Cp-U9ZVxe-l6:-NBCn_h09xq5DfntXEsm:bpli3j) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/e514a41ea5b03f3abe93b418ea87930b1604a286/scripts/test-certificate-verify.py#L99)):*
<details><summary><i>Previously, ep69 (Stanislav Židek) wrote…</i></summary><blockquote>

Could we simplify the whole `try ... except` block by using default value in getattr? Something like:`ciphers = [getattr(CipherSuite, arg, int(arg))]`
</blockquote></details>

would be, but the problem is that `int(arg)` would be called first, and if `arg` is text, then it would rise an exception...

**Review by ep69 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tomato42)

**Review by ep69 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/801)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tomato42)

**Pull request merged**
