### PR TITLE
Code Reuse - scripts/test-bleichenbacher-timing-pregenerate.py

### PR DESCRIPTION
**Pull request by nrathaus**
Code reuse

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853)

### CODE REVIEW

**Review by tomato42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @nrathaus)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOHg_G2O7ixhVIVXRF):*
this should be something like `bleichenbacher-timing-pregenerate: code reuse` or `test-bleichenbacher-timing-pregenerate.py: code deduplication`
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 98 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOHvgi-mFuFuUvuo4x:-NcOHvgi-mFuFuUvuo4y:b-2ni3oh) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L98)):*
> ```Python
> 
> 
> def initiate_connection(host, port, timeout, cipher, cln_extensions, srv_extensions, client_key_exchange_generator, level, alert):
> ```

while not a strict limit, I prefer the lines to be under 80 columns wide: it makes dealing with 3-way merges much easier
I also don't like the name of the function, it does not initiate any connections, it builds a decision graph, something like `default_conversation` or `build_conn_graph` would be more appropriate
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 111 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOIrbvELWN0h6zFpm3:-NcOIrbvELWN0h6zFpm4:b-wwrb5p) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L111)):*
> ```Python
>     node = node.add_child(TCPBufferingEnable())
>     node = node.add_child(client_key_exchange_generator)
>     cke_node = node
> ```

I don't think it's necessary to return the node that was passed in: they're passed by reference, not by value...
and add_child() just returns the value it was passed in to make combining multiple nodes together easier
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 119 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOIPqj3CZwL4ajgV1i:-NcOIPqj3CZwL4ajgV1j:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L119)):*
> ```Python
>                                       alert))
>     node.add_child(ExpectClose())
>     
> ```

nit: leftover spaces
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 120 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOJxQ7-KMU-aSV19mT:-NcOJxQ7-KMU-aSV19mU:b6atsqv) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L120)):*
> ```Python
>     node.add_child(ExpectClose())
>     
>     return (conversation, node, cke_node)
> ```

the `node` here is also not needed...
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 419 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOKFlY4Ni1HMW1rv0V:-NcOKFlY4Ni1HMW1rv0W:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L419)):*
> ```Python
>                                                          cipher, cln_extensions, srv_extensions,
>                                                          client_key_exchange_generator, level, alert)
>     
> ```

nit: leftover spaces
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 477 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOKLNg5OmpNhxUinWz:-NcOKLNg5OmpNhxUinX-:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L477)):*
> ```Python
>         padding_subs={2: 0},
>         reuse_encrypted_premaster=reuse_rsa_ciphertext)
>     
> ```

nit: leftover spaces
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 668 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOKUd56C6hkuW3eB_H:-NcOKUd56C6hkuW3eB_I:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L668)):*
> ```Python
>         for i in [1, 4, 8]:
>             # check if too short PKCS padding is detected
>             
> ```

nit: leftover spaces
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 676 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOK_4W0ePJt_HRHZ59:-NcOK_4W0ePJt_HRHZ5A:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L676)):*
> ```Python
>                 padding_subs[j] = 0
>             padding_subs[i+1] = 2
>             
> ```

nit: leftover spaces
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 733 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOKk6u3qgCmaZsl_jr:-NcOKk6u3qgCmaZsl_js:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L733)):*
> ```Python
>                                                          cipher, cln_extensions, srv_extensions,
>                                                          client_key_exchange_generator, level, alert)
>         
> ```

nit: leftover spaces
___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 781 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOKnTs6o7dBAscDlN1:-NcOKnTtEn4ng-muNgiB:b5ho0mw) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/891c9efeeecca239a9ba62c7afa4f36e41539f2c/scripts/test-bleichenbacher-timing-pregenerate.py#L781)):*
> ```Python
>     # test for Hamming weight sensitivity:
>     # very high Hamming weight:
>     
> ```

nit: leftover spaces

**Comment by tomato42** [comment]
also, when you implement the changes, please squash the commits together

**Comment by nrathaus** [comment]
Sorry, I am away this week

Will look into it next week (Sunday 27th)

Thanks,
Noam Rathaus

**Comment by nrathaus** [comment]
I copy pasted this code (that was reused), I returned 'node' and 'cke_node' because it was used
```
node = node.add_child(TCPBufferingEnable())
node = node.add_child(client_key_exchange_generator)
cke_node = node
```

At least in my opinion using 'return' make it explicit that you return it, avoiding confusion of whether its by 'value' or by 'ref', but if you disagree I will remove

**Comment by nrathaus** [comment]
I think I need to reopen the PR to squash the commits, as I don't see how to do it on an existing one - otherwise I implemened the changes you asked

I suggest we use something like 'black' or other linters to remove the spaces, break at 80 chars, rather than doing it manually, what do you think?

**Comment by tomato42** [comment]
> At least in my opinion using 'return' make it explicit that you return it, avoiding confusion of whether its by 'value' or by 'ref', but if you disagree I will remove

having it passed in and then gotten back suggests that it was modified and it's a different node now, that's not he case.
it was a different variable name previously because it's generated as part of the conversation but it's also needed for the pregeneration and it's cleaner to show that both the conversation and the new node are added to the dictionaries when they're together in code.

So, please, change it.

> I think I need to reopen the PR to squash the commits, as I don't see how to do it on an existing one - otherwise I implemened the changes you asked

you don't, as you've seen I've fixed the #837 without creating new PR. You need to rebase it in interactive mode on top of my master branch and make sure that only the appropriate commits are included while rebasing. After you do this, you can rebase it again and squash all the commits together and edit the commit message.

> I suggest we use something like 'black' or other linters to remove the spaces, break at 80 chars, rather than doing it manually, what do you think?

I'm not against using black (in fact, I *am* using it with https://github.com/tlsfuzzer/python-ecdsa), but I'm afraid that it will introduce a lot of changes so it will be too aggressive for the refactor patch. I suggest to make your editor show the whitespace caracters and the 80 column line, it will be much easier to fix.

**Comment by nrathaus** [comment]
I took the following steps, let me know if this is what you intended (sorry I am new to this, I am more used to gitlab where you can squash in the UI):
```
git fetch upstream
git rebase -i upstream/master
```

I picked only my changes

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853)* status: all files reviewed, 3 unresolved discussions (waiting on @nrathaus)

___
*[`scripts/test-bleichenbacher-timing-pregenerate.py` line 111 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853#-NcOIrbvELWN0h6zFpm3:-Nd5LfBw91z4mu1sdHUq:bwt1byi) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/4d0aa240a1cebd7b6d2ba268a6f56e5158774dff/scripts/test-bleichenbacher-timing-pregenerate.py#L111)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

I don't think it's necessary to return the node that was passed in: they're passed by reference, not by value...
and add_child() just returns the value it was passed in to make combining multiple nodes together easier
</blockquote></details>

still not fixed

**Comment by tomato42** [comment]
> let me know if this is what you intended

yes, that's precisely what I expected for the rebase

> sorry I am new to this, I am more used to gitlab where you can squash in the UI

yeah, github UI is pretty atrocious for doing anything, I avoid it as much as possible (basically I do just merges through UI, everything else I do using CLI tools)

**Comment by tomato42** [comment]
also, don't worry about the test failure with
`DEBUG:root:Killing server process`
`INFO:root:Server process killed: -11`
that's a known issue (#788); I'll rerun them if that happens for the final version

**Comment by tomato42** [comment]
sorry, I haven't merged because https://github.com/tlsfuzzer/tlsfuzzer/pull/853#pullrequestreview-1602564690 isn't addressed... I was waiting for you...

**Comment by nrathaus** [comment]
Hi,

Can you re-review the file? the function now does not return `node`

I hope I understood correctly what you meant

**Comment by nrathaus** [comment]
The code on my branch currently has:
```
def build_conn_graph(host, port, timeout, cipher, cln_extensions,
                     srv_extensions, client_key_exchange_generator, level,
                     alert):
    """ Reuse the same block as a function, to simplify code """
    conversation = Connect(host, port, timeout=timeout)
    node = conversation
    ciphers = [cipher]
    node = node.add_child(ClientHelloGenerator(ciphers,
                                               extensions=cln_extensions))
    node = node.add_child(ExpectServerHello(extensions=srv_extensions))

    node = node.add_child(ExpectCertificate())
    node = node.add_child(ExpectServerHelloDone())
    node = node.add_child(TCPBufferingEnable())
    node = node.add_child(client_key_exchange_generator)
    cke_node = node
    node = node.add_child(ChangeCipherSpecGenerator())
    node = node.add_child(FinishedGenerator())
    node = node.add_child(TCPBufferingDisable())
    node = node.add_child(TCPBufferingFlush())
    node = node.add_child(ExpectAlert(level, alert))
    node.add_child(ExpectClose())

    return (conversation, cke_node)
```

**Comment by tomato42** [comment]
Yes, and that's why I have issue with: the `cke_node` in return is unnecessary when it's exactly the same one as in `client_key_exchange_generator` that was passed in

**Comment by nrathaus** [comment]
Now I understand, sorry I missed that part - because I couldn't properly debug the code in VS

See my latest commit

BTW if someone looks this up, the VS code to get it to work is:
```
"configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "env": {
                "PYTHONPATH": "${workspaceFolder}"
            },
            "args": ["-h", "badssl.com", "-p", "443"]
        }
    ]
 ```

**Comment by tomato42** [comment]
You've merged the main branch to to this PR, _please_ don't do it. If you want to update it, _rebase_ the PR, never merge master into a branch.

**Review by tomato42 — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853)* status: all files reviewed, 1 unresolved discussion (waiting on @nrathaus)

**Review by tomato42 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nrathaus)

**Pull request merged**
