### PR TITLE
Code Reuse - scripts/test-rsa-pss-sigs-on-certificate-verify

### PR DESCRIPTION
**Pull request by nrathaus**
Joining a few graph constructions into a function the code is reduced - making it also easier to read

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867)

### CODE REVIEW

**Comment by tomato42** [comment]
Please [rebase](https://help.github.com/articles/about-git-rebase/) your PR on top of current master branch, then [force push](https://stackoverflow.com/a/10510482/462370) to the same branch as this PR is using.

Do not merge the `master` branch to this branch to update it, it will cause failures in CI.

**Comment by nrathaus** [comment]
I did as follows, let me know if this what you meant (during the rebase I verified its only my changes):
```
git rebase --interactive upstream/master
git push --force
```

**Comment by tomato42** [comment]
you should also `git fetch upstream` as the first step, so that you're rebasing on top of current master

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867)* status: all files reviewed, 2 unresolved discussions (waiting on @nrathaus)

___
*[`-- commits` line 14 at r5](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867#-NgKTJjz7UaTtGSODrNX):*
those two patches need to be combined into one; to do that, while doing git rebase, mark this one as `fixup` instead of `commit`
___
*[`scripts/test-rsa-pss-sigs-on-certificate-verify.py` line 69 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867#-NgKN-CrArdZu_kUu8bB:-NgKN-CrArdZu_kUu8bC:bmvxy48) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/a551ccab4a368d466549673e8a44d721d4eb3252/scripts/test-rsa-pss-sigs-on-certificate-verify.py#L69)):*
> ```Python
> 
> 
> def build_connection_graph(host, port, ciphers, ext, cert, certificate_verify_generator,
> ```

I may be missing something, but `ciphers` should be the same for all connections...
the differences for `ext` test case to test case should also be minimal, and limited to one or two extensions

**Comment by nrathaus** [comment]
Should be more clean now

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867)* status: all files reviewed, 3 unresolved discussions (waiting on @nrathaus)

___
*[`-- commits` line 2 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867#-NgOW0uD5whDlIxucjnS):*
Yes, combining all into one is also an option, but then the commit description should reflect that.
___
*[`scripts/test-rsa-pss-sigs-on-certificate-verify.py` line 238 at r6](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867#-NgOVob74QIml3pIxKPm:-NgOVob74QIml3pIxKPn:bw0ijhl) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/c8f4be746328a1ce0e016e19ff229b7c7b1fa1d6/scripts/test-rsa-pss-sigs-on-certificate-verify.py#L238)):*
> ```Python
>             ]
> 
>     ext = {ExtensionType.signature_algorithms:
> ```

it's unused code now

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/867)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nrathaus)

**Pull request merged**
