### PR TITLE
tlsfuzzer/analysis.py: reshuffled bit size smart analysis

### PR DESCRIPTION
**Pull request by GeorgePantelakis**
### Description
Reshuffled code in smart analysis to be more reliable and do more randomization of the data for cleared results.

### Motivation and Context
Solves [issue#921](https://github.com/tlsfuzzer/tlsfuzzer/issues/921)

### Checklist
- [x] I have read the [CONTRIBUTING.md](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md) document and my PR follows [change requirements](https://github.com/tlsfuzzer/tlsfuzzer/blob/master/CONTRIBUTING.md#change-requirements) therein
- [x] all new and existing tests pass (see CI results)

- - -
This change is [Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926)

### CODE REVIEW

**Comment by GeorgePantelakis** [comment]
PR ready for review

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 1813 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926#-NzEE8n96-YxZeYPNx-u:-NzEE8n96-YxZeYPNx-v:b-wri3v6) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/12f311a0bef97f0ae7730c1bbe37cbb7cc9c350b/tlsfuzzer/analysis.py#L1813)):*
> ```Python
>                 # dozen megabytes of data to work with
>                 self._k_sizes_totals_worker,
>                 ((k_sizes, i) for i in _slices(total_data, 1024*1024*64))
> ```

I worry that the `k_sizes` here are passed in by value to the workers, not by reference...
___
*[`tlsfuzzer/analysis.py` line 2239 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926#-NzE8tFU91EY9U_IFeIs:-NzE8tFU91EY9U_IFeIt:b-fe040k) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/12f311a0bef97f0ae7730c1bbe37cbb7cc9c350b/tlsfuzzer/analysis.py#L2239)):*
> ```Python
> 
>         with open(join(self.output, "timing.csv"), 'w') as fp:
>             fp.write('256,255\n')
> ```

should that really be hardcoded?
___
*[`tlsfuzzer/analysis.py` line 2324 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926#-NzE6r499zI8z-d5gyWs:-NzE6r499zI8z-d5gyWt:b8ybb4c) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/12f311a0bef97f0ae7730c1bbe37cbb7cc9c350b/tlsfuzzer/analysis.py#L2324)):*
> ```Python
> 
>         samples_in_timing_files = self.create_k_specific_dirs()
>         print(samples_in_timing_files)
> ```

leftover debug?

**Review by tomato42 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926)* status: all files reviewed, 3 unresolved discussions (waiting on @GeorgePantelakis)

**Review by tomato42 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926)* status: all files reviewed, 2 unresolved discussions (waiting on @GeorgePantelakis)

___
*[`tlsfuzzer/analysis.py` line 2239 at r1](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926#-NzE8tFU91EY9U_IFeIs:-NzEg25x3VFOosVDlmTc:blzd5h9) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/12f311a0bef97f0ae7730c1bbe37cbb7cc9c350b/tlsfuzzer/analysis.py#L2239)):*
<details><summary><i>Previously, tomato42 (Hubert Kario) wrote…</i></summary><blockquote>

should that really be hardcoded?
</blockquote></details>

not fixed?
___
*[`tlsfuzzer/analysis.py` line 2190 at r2](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926#-NzEfwmqDNomYdPfEq2K:-NzEfwmqDNomYdPfEq2L:b8ybb4c) ([raw file](https://github.com/tlsfuzzer/tlsfuzzer/blob/28be854dbc7c7e587e63eaded35dbdf6020097d2/tlsfuzzer/analysis.py#L2190)):*
> ```Python
>         values = data['value']
> 
>         print(k_sizes)
> ```

leftover debug?

**Review by tomato42 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tlsfuzzer/tlsfuzzer/926)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GeorgePantelakis)

**Pull request merged**
